name: aic
services:
  eval:
    image: ghcr.io/intrinsic-dev/aic/aic_eval
    build:
      dockerfile: docker/aic_eval/Dockerfile
      context: ..
    command: gazebo_gui:=false launch_rviz:=false
    gpus: all
    networks:
      - default
  model:
    image: ghcr.io/intrinsic-dev/aic_model
    build:
      dockerfile: docker/aic_model/Dockerfile
      context: ..
    command: --ros-args -p policy:=aic_example_policies.ros.WaveArm
    gpus: all
    networks:
      - default
    environment:
      RMW_IMPLEMENTATION: rmw_zenoh_cpp
      ZENOH_CONFIG_OVERRIDE: connect/endpoints=["tcp/eval:7447"];routing/router/peers_failover_brokering=true
      ZENOH_ROUTER_CHECK_ATTEMPTS: -1
networks:
  default:
    internal: true
